sudo: required
language: node_js
node_js:
- '4'
python:
- '2.7'
env:
- CXX=g++-4.8
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
#  sauce_connect:
#    username: autodesk-bionano
#    access_key:
#      secure: Obz8aK8m9hKMfiNicD/IWBnYVC5PqLLoTfgpM31ppaGsgpd+//YMrGqgcPQY91m5TRpgmNsYRsEKKnv2yKa8ALxCZ0i0VZCZwuFCG8Zgld78RiiAli+gJISeEPqR+Js+Txz0nf1y1WYyzocfl14/cqGq9cpnhEa9Lkz618C+KZFqXuLo4P0oAf76GnM5/SE7d6dyZ8p1FMGSBendb1fn4lWEa7oAIaeoTOZzVeJeIYptjKGCd5PqE6rN7T1QVZBnpUV1OhmjcAZprRUQNFvD+2aM+LtxG2HUB1LcJAI07PhcU8rLAtE96ZJMsJj0/XRzeMTi+JF/rN7bZh5R+wlNO/jiCIRFT00I2+jKWWzXwxHLUBxcujN/ky5L8cAHq6gXQo+brgQFJifzgls2YMIn2KPqk0Q31gG7hoDOBlK4NN5a6sSzkFewdd4KWqf1iilcbVdSlkM2/yohIMTq5Vvuq0GI8XUFnRUC4+qvcBKmRa9fYzCTv2v5zA4LaR+VdsnzYg8I1ahY4RwADewP1INMD2lqxNt3tFQQKmgrxEYOCrpR3gdI5gDxCpYcgsO5+TOmr94ZE4GLr2JbCTPAxVi8ZOAv5r0JoY1+0GDT+m1UaxlpybMezXmy2/64uy+ru8Z0aUBkFfUBzgGYfOvlRSZJTTPIcYsQyHpm+i/++HtHqp4=
install:
- npm install
script:
- npm run lint
- npm run test
- npm run test-coverage-report
#- npm run start-testing; npm run nightwatch-saucelabs; pkill node
cache:
  directories:
  - node_modules
notifications:
  email: false
  slack:
    secure: JOZIqZ8s4vFEtmgMYSy6TlVqIXiyjDWYhdkxIRg4SlXwcD/akuXM6Zn8S9J5kbmLcA7swZ5Z7Pu+v7Zhkq9MlJd09Dj2ROYBg9fL8biLhfte9WUK9lG/uAoNmOLeAApzhUhLRnXJR6lY7hPfUCUW5iWVWWvBbVKz6aw5MORaoasO097IHkmUZhVZdnajfZ5NFEc4EIyrZ/tn3ovR+eYg8zqdtUOsA+xY7+568bcg5gBqeY/zjTBVIrgoZ87j4/OdEQ/35v57iTQSc28O/uGBLg8c3NBxp+pvhueMWMkPyqzm4QacU0x3N3uOE2/9MZdicyW9+J99xe/19O/xrxkjrBWPDASdYIhCfhY9X/TzQmZ3xnIDR7KzW2cE5H5hrhxFnXc6hZ2hALkmA7QyV7mBnBGH09LHdDpB0yczdz+Xp42UQSCIag71dJRxDpO2FV+FRfQdrWAbFt5IVN0tll6OqX7DyI8gvo9YmjCSt5ZTWPm8YcW/GALwAD/oNt2mZSReMaRPjpzous3yLoF0++/MGJ0w4w80P3bMgoOLJX137vm4jXh0e1ZPDBTcmNK8XKZCdfljq0FPkp2ny80I+cdf6JjX3oNmcTpdrSVB4RYjosVjH/jl+pj1hBK+p4qf63BSmWLbc+uBT6k3eKPEE1g7RqmVvefPwfki8J1TO2chM2Q=
